"""Thought module containing Thought and ThoughtReservoir classes."""
from typing import Dict, List, Optional, Any, Tuple
from datetime import datetime
from .utils.vector_store import VectorStore, StoredItem

class Thought:
    """A thought generated by an agent."""
    
    def __init__(
        self,
        id: str,
        content: Dict[str, Any],
        type: int,
        stimuli: List[str],
        intrinsic_motivation: Dict[str, Any],
        turn_number: int = 0
    ):
        """Initialize a thought.
        
        Args:
            id: Unique identifier for the thought
            content: Dictionary containing text and embedding
            type: System type (1 or 2)
            stimuli: List of memory or thought IDs that triggered this thought
            intrinsic_motivation: Dictionary with reasoning text and score
            turn_number: Turn number when this thought was generated
        """
        self.id = id
        self.content = content
        self.type = type
        self.stimuli = stimuli
        self.intrinsic_motivation = intrinsic_motivation
        self.turn_number = turn_number
        self.saliency = 1.0
        self.created_at = datetime.now()
        self.last_accessed = self.created_at
        self.retrieval_count = 0
        self.expression = None  # ID of utterance if expressed
        self.evolution_history = []  # Track thought evolution
        self.last_accessed_turn = turn_number

class ThoughtReservoir:
    """Manages a collection of thoughts using FAISS for efficient retrieval."""
    
    def __init__(self, embedding_dim: int = 1536):
        """Initialize an empty thought reservoir.
        
        Args:
            embedding_dim: Dimension of embeddings (default: 1536 for text-embedding-3-small)
        """
        self.vector_store = VectorStore(embedding_dim)
        
    def add(self, thought: Thought) -> None:
        """Add a new thought to the reservoir.
        
        Args:
            thought: Thought to add
        """
        self.vector_store.add_item(
            item_id=thought.id,
            embedding=thought.content["embedding"],
            content=thought.content,
            metadata={
                "type": thought.type,
                "stimuli": thought.stimuli,
                "intrinsic_motivation": thought.intrinsic_motivation,
                "saliency": thought.saliency,
                "last_accessed_turn": thought.last_accessed_turn,
                "retrieval_count": thought.retrieval_count,
                "expression": thought.expression,
                "evolution_history": thought.evolution_history
            },
            turn_number=thought.turn_number
        )
        
    def retrieve(
        self,
        query_embedding: Optional[List[float]] = None,
        filter_fn: Optional[callable] = None,
        min_similarity: float = 0.7,
        turn_window: Optional[Tuple[int, int]] = None,
        top_k: int = 5
    ) -> List[Tuple[Thought, float]]:
        """Retrieve thoughts, optionally filtered by similarity and custom function.
        
        Args:
            query_embedding: Optional embedding to find relevant thoughts
            filter_fn: Optional function to filter thoughts (takes Thought, returns bool)
            min_similarity: Minimum similarity threshold for semantic search
            turn_window: Optional (start_turn, end_turn) to filter results
            top_k: Maximum number of results to return
            
        Returns:
            List of (thought, similarity_score) tuples
        """
        if query_embedding is None:
            # Return most recent thoughts if no query
            items = []
            for idx, item in self.vector_store.stored_items.items():
                if turn_window is None or (turn_window[0] <= item.turn_number <= turn_window[1]):
                    items.append((item, 1.0))  # Default similarity of 1.0
            items.sort(key=lambda x: x[0].turn_number, reverse=True)
            items = items[:top_k]
        else:
            # Search by similarity
            items = self.vector_store.search(
                query_embedding=query_embedding,
                k=top_k,
                min_similarity=min_similarity,
                turn_window=turn_window
            )
            
        # Convert to Thoughts and apply filter
        results = []
        for item, similarity in items:
            thought = Thought(
                id=item.id,
                content=item.content,
                type=item.metadata["type"],
                stimuli=item.metadata["stimuli"],
                intrinsic_motivation=item.metadata["intrinsic_motivation"],
                turn_number=item.turn_number
            )
            thought.saliency = item.metadata["saliency"] * similarity
            thought.last_accessed_turn = item.metadata["last_accessed_turn"]
            thought.retrieval_count = item.metadata["retrieval_count"] + 1
            thought.expression = item.metadata["expression"]
            thought.evolution_history = item.metadata["evolution_history"]
            
            if filter_fn is None or filter_fn(thought):
                # Update metadata
                self.vector_store.update_metadata(item.id, {
                    "last_accessed_turn": thought.last_accessed_turn,
                    "retrieval_count": thought.retrieval_count,
                    "saliency": thought.saliency
                })
                results.append((thought, similarity))
                
        return sorted(results, key=lambda x: x[1], reverse=True)[:top_k]