"""Thought module containing Thought and ThoughtReservoir classes."""
from typing import List, Optional, Dict, Any, Tuple
from datetime import datetime
import uuid
import numpy as np
from numpy.typing import NDArray
from .utils import get_embedding

class Thought:
    """A thought generated by an agent.
    
    Attributes:
        id: Auto-generated unique identifier for the thought (format: "thought-{uuid}")
        agent_id: ID of the agent who generated the thought
        text: The text content of the thought
        embedding: Vector representation of the text as numpy array
        weight: Importance score of the thought predefined by user
        type: System type (1 or 2)
        stimuli: List of memory or thought IDs that triggered this thought
        intrinsic_motivation: Dictionary with reasoning text and score  
        turn_number: Turn number when this thought was generated
        utterance_id: Optional ID of utterance if expressed

        saliency: Importance score of the thought
        retrieval_count: Number of times this thought has been retrieved
        last_accessed_turn: Last turn number when this thought was retrieved
    """
    
    def __init__(
        self,
        agent_id: str,
        text: str,
        embedding: NDArray[np.float32],
        type: int,
        stimuli: List[str],
        intrinsic_motivation: Dict[str, Any],
        weight: float = 1.0,
        turn_number: int = 0,
        utterance_id: Optional[str] = None
    ) -> None:
        """Initialize a thought.
        
        Args:
            agent_id: ID of the agent who generated the thought
            text: The text content of the thought
            embedding: Vector representation of the text
            type: System type (1 or 2)
            stimuli: List of memory or thought IDs that triggered this thought
            intrinsic_motivation: Dictionary with reasoning text and score
            weight: Importance score predefined by user (default: 1.0)
            turn_number: Turn number when this thought was generated
            utterance_id: Optional ID of utterance if expressed
        """
        self.id = f"thought-{uuid.uuid4()}"
        self.agent_id = agent_id
        self.text = text
        self.embedding = embedding
        self.weight = weight
        self.type = type
        self.stimuli = stimuli
        self.intrinsic_motivation = intrinsic_motivation
        self.turn_number = turn_number
        self.utterance_id = utterance_id

        # Tracking metrics
        self.saliency = 1.0
        self.retrieval_count = 0
        self.last_accessed_turn = turn_number

class ThoughtReservoir:
    """Manages a collection of thoughts.
    
    Maintains a list of thoughts with methods for adding new thoughts
    and retrieving relevant ones based on similarity or recency.
    
    Attributes:
        thoughts: List of all thoughts
    """
    
    def __init__(self) -> None:
        """Initialize an empty thought reservoir."""
        self.thoughts: List[Thought] = []
        
    async def add_thought(self, agent_id: str, text: str, type: int, stimuli: List[str], intrinsic_motivation: Dict[str, Any], weight: float = 1.0, turn_number: int = 0, utterance_id: Optional[str] = None) -> None:
        """Add a new thought with generated embedding.
        
        Args:
            agent_id: ID of the agent who generated the thought
            text: The text content of the thought
            type: System type (1 or 2)
            stimuli: List of memory or thought IDs that triggered this thought
            intrinsic_motivation: Dictionary with reasoning text and score
            weight: Importance score predefined by user (default: 1.0)
            turn_number: Turn number when this thought was generated
            utterance_id: Optional ID of utterance if expressed
            
        Raises:
            ValueError: If text is empty
            LLMAPIError: If embedding generation fails
        """
        if not text.strip():
            raise ValueError("Empty text provided for thought")
            
        # Generate embedding from text
        embedding_list = await get_embedding(text)
        embedding = np.array(embedding_list, dtype=np.float32)
        
        # Create thought
        thought = Thought(
            agent_id=agent_id,
            text=text,
            embedding=embedding,
            type=type,
            stimuli=stimuli,
            intrinsic_motivation=intrinsic_motivation,
            weight=weight,
            turn_number=turn_number,
            utterance_id=utterance_id
        )
        
        # Add to thought reservoir
        self.thoughts.append(thought)
   
    # TODO: Implement retrieval methods